packaging_format = 2

id = "selfoss"
name = "Selfoss"
description.en = "Multipurpose RSS reader"
description.fr = "Lecteur RSS polyvalent"

version = "2.19~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
website = "https://selfoss.aditu.de/"
admindoc = "https://github.com/fossar/selfoss/wiki"
userdoc = "https://selfoss.aditu.de/"
code = "https://github.com/fossar/selfoss"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/selfoss"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/SSilence/selfoss/releases/download/2.19/selfoss-2.19.zip"
        sha256 = "e49c4750e9723277963ca699b602f09f9148e2b9f258fce6b14429498af0e4fc"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "sqlite3 php8.0-xml php8.0-sqlite3 php8.0-mbstring php8.0-mysql php8.0-gd php8.0-curl"
